### ISSUE TITLE
How to access robots.txt file ?

### ISSUE THREAD

**Issue by ggarg2** [patrickmichalina/fusebox-angular-universal-starter#107]
Hi Team,

I am new in universal. How to access robots.txt file  like  we are accessing sitemap.xml?

**Comment by patrickmichalina** [comment]
Thanks for reporting. You are right, I overlooked this. Will update today.

**Comment by patrickmichalina** [comment]
@ggarg2 please check the fix, straightforward!

**Comment by ggarg2** [comment]
@patrickmichalina thanks boss. This issue is fixed.

**Comment by patrickmichalina** [comment]
@ggarg2 i will be updating this again to use

```js
app.use('/robots.txt', express.static('dist/robots.txt', staticOptions));
```

just a heads up!

**Comment by ggarg2** [comment]
okay. Commit the code i will test it.
