### ISSUE TITLE
Dependencies not available in build.interfaces.ts

### ISSUE THREAD

**Issue by ggarg2** [patrickmichalina/fusebox-angular-universal-starter#117]
Hi @patrickmichalina 

i am using visual studio code.  I am not able to find these dependencies in "Dependency, DependencyType, SourceType" in build.interfaces.ts file but code is working.

**Comment by patrickmichalina** [comment]
That structure was removed in favor of a simpler interface, so those interfaces no longer. Where do you see the errors?

**Comment by ggarg2** [comment]
In build.tranformer.ts

**Comment by patrickmichalina** [comment]
ok will check it out thanks

**Comment by patrickmichalina** [comment]
Oh right, I moved this work into its own fusebox plugin:

https://github.com/patrickmichalina/fusebox-angular-universal-starter/blob/master/tools/plugins/web-index.ts

forgot to clean all this up :)

**Comment by ggarg2** [comment]
oh okay. I am learning many new things from your project. Thanks for awesome project :)

**Comment by patrickmichalina** [comment]
Thanks! I am glad it is helping you. I have more features, fixes, and documentation in coming soon.

**Comment by ggarg2** [comment]
Awesome :) 
I am also trying to introduce rich material design in project.
I will be glad if there is anything I can use my skills to help you.

**Comment by patrickmichalina** [comment]
I was thinking about including Angular Material but it doesn't 100% support universal rendering yet. If you figure it out and want to redesign the starter to be prettier, please submit a pull request.

**Comment by ggarg2** [comment]
Okay i am in a learning stage. I will try to implement Angular Material in project.
