### ISSUE TITLE
"Cannot find module 'node-zopfli'" error

### ISSUE THREAD

**Issue by merihs** [patrickmichalina/fusebox-angular-universal-starter#127]
After the latest update I get "Cannot find module 'node-zopfli'" error.
I think it is related with this issue. #123

Platform : Windows 10
Node version : 8.4.0
Npm version : 5.3.0
Python version : 2.7.13

```
[Browsersync] Proxying: http://localhost:8001
[Browsersync] Access URLs:
 ------------------------------------
       Local: http://localhost:8000
    External: http://192.168.1.5:8000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.5:3001
 ------------------------------------
module.js:491
    throw err;
    ^

Error: Cannot find module 'node-zopfli'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Development\Workspaces\TESTS\Universal\patrickmichalina\fusebox-angular-universal-starter\node_modules\shrink-ray\index.js:31:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

Typechecker plugin(async) :App typechecker.
Time:Sun Sep 03 2017 23:58:43 GMT+0300 (Russia TZ 2 Standard Time)
All good, no errors :-)
Typechecking time: 15738ms
Quiting typechecker

killing worker
```

**Comment by patrickmichalina** [comment]
Thought it would fix it :/

How about you try `npm install --global --production windows-build-tools ` from an elevated command prompt, then reinstall the project dependencies?

**Comment by patrickmichalina** [comment]
see: https://github.com/nodejs/node-gyp#installation

**Comment by merihs** [comment]
@patrickmichalina  I installed node-gyp following the article but I still get the same error. I used similar solution which bluelightning2k described in the issue #123 to fix it..
I removed shrinkRay from package.json and server.ts and I directly used app.use(compression()) and it worked.

**Comment by patrickmichalina** [comment]
@merihs please try latest code changes, I think this will work (but I don't have a vm setup to test this on). Thanks for your patience.
