### ISSUE TITLE
Using css instead of sass.

### ISSUE THREAD

**Issue by merihs** [patrickmichalina/fusebox-angular-universal-starter#147]
I get "TypeError: cssText.replace is not a function" error when I directly use css files in the project.

**Comment by patrickmichalina** [comment]
You mean when using the `@import` syntax?

You have to drop the .css in the file name in order to import raw CSS.

example:
```scss
@import '../../../node_modules/bootstrap/dist/css/bootstrap'; 
```

**Comment by merihs** [comment]
No I mean when I change app.component.scss to app.component.css and import it in app.component.ts like styleUrls: ['./app.component.css'] it returns "TypeError: cssText.replace is not a function' error.

**Comment by patrickmichalina** [comment]
Ahh ok, you cannot do that in the current setup. This build forces you you use SCSS. If you need to change that, please check the fuse.ts file and the app plugins section.

I do not recommend you do this, since SCSS supports using css.

**Comment by merihs** [comment]
Thanks :) you right. I don't know sass so I didn't want to use it but you are right. If it supports using css in scss file, there is no problem.

Thank you so much
