### ISSUE TITLE
Http get request page reloading issue

### ISSUE THREAD

**Issue by ggarg2** [patrickmichalina/fusebox-angular-universal-starter#158]
Hi @patrickmichalina 

I have created one method in search.component.ts file.
search(q: string){
    this.$results = this.searchService.search(q);
    this.$items = this.$results.map((a: any) => a.items)
    this.$count = this.$results.map((a: any) => a.total_count)
  }
 public search(search: string, sort = '', order = ''): Observable<any> {
    const params = new HttpParams()
      .set('q', search)
      .set('sort', sort)
      .set('order', order)
      return this.http.get(this.url, { withCredentials: false, params  })
  }
`<form class="form-inline">`
        `<div class="form-group mx-lg-3">`
`            <input #query type="text" class="form-control" placeholder="Search Angular projects">`
        `</div>`
        `<button (click)="search(query.value)">Search</button>`
   `</form>`
when i am calling  this method, i can see the result but after result,  page is reloading automatically.
can we send ajax request with form tag without reloading the page ?

**Comment by patrickmichalina** [comment]
I think is the default behavior of buttons inside a form. You should try checking onSubmit behavior (more of an HTML concern). I didn't spend much time on this part of the demo and will probably remove it in favor of an API from the node server. Let me know if you need more help. Thanks!

**Comment by ggarg2** [comment]
i guess only solution to use form without reloading page is FormsModule

`<form #searchForm="ngForm" (ngSubmit)="search(query.value)" class="form-inline">`
`        <div class="form-group mx-lg-3">`
 `           <input #query type="text" class="form-control" placeholder="Search Angular projects">`
`        </div>`
        `<button type="submit">Search</button>`
    `</form>`
