### ISSUE TITLE
Sitemap - Internal Server Error

### ISSUE THREAD

**Issue by ggarg2** [patrickmichalina/fusebox-angular-universal-starter#159]
Hi @patrickmichalina 

This url http://localhost:8000/sitemap.xml  is throwing internal server error

starting sitemap crawler on http://localhost:8000:8001
{"name":"Angular Universal App","type":"http-access","hostname":"goku","pid":11596,"req_id":"68d22470-97fa-11e7-b975-7362ef7b543f","level":30,"res":{"statusCode":200,"header":"HTTP/1.1 200 OK\r\nX-Powered-By: Express\r\nX-Request-Id: 68d22470-97fa-11e7-b975-7362ef7b543f\r\nExpires: Tue, 12 Sep 2017 20:39:01 GMT\r\nAccept-Ranges: bytes\r\nCache-Control: public, max-age=0\r\nLast-Modified: Tue, 12 Sep 2017 20:38:49 GMT\r\nETag: W/\"17-15e77d0db77\"\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 23\r\nVary: Accept-Encoding\r\nDate: Tue, 12 Sep 2017 20:39:01 GMT\r\nConnection: close\r\n\r\n"},"duration":6.628807999999999,"req":{"method":"GET","url":"/robots.txt","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","user-agent":"Node/SitemapGenerator","host":"localhost:8001","accept-encoding":"gzip, deflate","referer":"http://localhost:8001/:8000","connection":"close"},"query":{}},"msg":"request finish","time":"2017-09-12T20:39:01.438Z","v":0}
{"name":"Angular Universal App","type":"http-access","hostname":"goku","pid":11596,"req_id":"68dbc160-97fa-11e7-b975-7362ef7b543f","level":30,"res":{"statusCode":404,"header":"HTTP/1.1 404 Not Found\r\nX-Powered-By: Express\r\nX-Request-Id: 68dbc160-97fa-11e7-b975-7362ef7b543f\r\nContent-Type: text/html; charset=utf-8\r\nETag: W/\"2abc-OBpPuQM+bk1LVVi1fFtNECPN9A8\"\r\nVary: Accept-Encoding\r\nContent-Encoding: gzip\r\nDate: Tue, 12 Sep 2017 20:39:01 GMT\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n"},"duration":51.517874,"req":{"method":"GET","url":"/:8000","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","user-agent":"Node/SitemapGenerator","host":"localhost:8001","accept-encoding":"gzip, deflate","connection":"close"},"query":{}},"msg":"request finish","time":"2017-09-12T20:39:01.546Z","v":0}
{"name":"Angular Universal App","type":"http-access","hostname":"goku","pid":11596,"req_id":"68caaa60-97fa-11e7-b975-7362ef7b543f","level":30,"res":{"statusCode":500,"header":"HTTP/1.1 500 Internal Server Error\r\nX-Powered-By: Express\r\nX-Request-Id: 68caaa60-97fa-11e7-b975-7362ef7b543f\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 21\r\nETag: W/\"15-/6VXivhc2MKdLfIkLcUE47K6aH0\"\r\nVary: Accept-Encoding\r\nDate: Tue, 12 Sep 2017 20:39:01 GMT\r\nConnection: close\r\n\r\n"},"duration":287.854737,"req":{"method":"GET","url":"/sitemap.xml","headers":{"accept-language":"en-GB,en-US;q=0.8,en;q=0.6","accept-encoding":"gzip, deflate, br","referer":"http://localhost:8000/","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36","upgrade-insecure-requests":"1","connection":"close","host":"localhost:8001"},"query":{},"remoteAddress":"::ffff:127.0.0.1","remotePort":60989},"msg":"request finish","time":"2017-09-12T20:39:01.669Z","v":0}

**Comment by patrickmichalina** [comment]
Ahh wow my bad. This is a bug. Thanks!
