### ISSUE TITLE
Extend NgLazy plugin to support nested lazy modules

### ISSUE THREAD

**Issue by patrickmichalina** [patrickmichalina/fusebox-angular-universal-starter#192]

**Comment by ggarg2** [comment]
Hi @patrickmichalina 

I am trying to run nested lazy modules with latest update but i am facing one issue. Please try my fork repository. https://github.com/ggarg2/fusebox-angular-universal-starter

{"name":"Angular Universal App","type":"http-access","hostname":"goku","pid":10380,"level":30,"msg":"Angular Universal Server listening at http://localhost:8000:8001","time":"2017-09-25T21:18:09.426Z","v":0}
{ name: 'Angular Universal App',
  type: 'app',
  hostname: 'goku',
  pid: 10380,
  level: 50,
  err:
   { msg: 'Uncaught (in promise): failed to load HomeModule',
     url: '/',
     stack: 'resolvePromise()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:795:31\nresolvePromise()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:766:17\n{anonymous}()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:844:17\nZoneDelegate.invokeTask()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:425:31\nObject.onInvokeTask()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\packages\\core\\esm5\\src\\zone\\ng_zone.js:576:10\nZoneDelegate.invokeTask()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:424:36\nZone.runTask()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:192:47\ndrainMicroTaskQueue()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:602:35\nZoneTask.invokeTask()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:503:21\nServer.ZoneTask.invoke()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:488:48\nemitTwo()@events.js:125:13\nServer.emit()@events.js:213:7\nparserOnIncoming()@_http_server.js:602:12\nHTTPParser.parserOnHeadersComplete()@_http_common.js:116:23' },
  config:
   { name: 'Fusebox Angular Universal Starter',
     description: 'Seed project for Angular Universal apps featuring Server-Side Rendering (SSR), FuseBox, dev/prod builds, Brotli/Gzip, SCSS, favicon generation, @types, unit testing w/ Jest, and sitemap generator. Created by Patrick Michalina',
     pageTitleSeparator: ' - ',
     endpoints: { api: 'http://localhost:1338/api' },
     og:
      { defaultSocialImage: 'https://d3anl5a3ibkrdg.cloudfront.net/assets/favicons/android-chrome-512x512.png',
        facebookAppId: '117309532219749' },
     host: 'http://localhost:8000',
     env: 'dev' },
  msg: 'Uncaught (in promise): failed to load HomeModule',
  time: 2017-09-25T21:18:09.991Z,
  v: 0 }
