### ISSUE TITLE
Firebase initialise App

### ISSUE THREAD

**Issue by ravivit9** [patrickmichalina/fusebox-angular-universal-starter#249]
Hi,

I would like to know where to setup Firebase initialise App.

Thanks,

**Comment by patrickmichalina** [comment]
Do you mean how to setup a firebase account?

https://firebase.google.com/

**Comment by ravivit9** [comment]
Hi, thanks for your reply. No not for firebase setup.

Actually I am using angular-seed as my repo. Happened to see your seed as well looks like the same (sorry if not the same). I am getting unexpected token error when initialise the app in app.module.ts after specifying firebase and angularfire2 path in project.conf.ts under tools/config.

**Comment by patrickmichalina** [comment]
Oh can you also try setting those values in https://github.com/patrickmichalina/fusebox-angular-universal-starter/blob/master/src/server/data/seed.settings.json

I am still playing around with what this seed will be.... its been shifting a lot :)

**Comment by patrickmichalina** [comment]
@ravivit9 any luck? this thread might help as well #250

**Comment by ravivit9** [comment]
@patrickmichalina, not yet.
When I tried with an another template the latest firebase and angularfire2 RC3 works fine.  Only problem is it's not working in angular-seed.

https://stackblitz.com/edit/angular-template-firebase?file=app%2Fapp.module.ts

**Comment by ravivit9** [comment]
I have integrated pretty much using angular-seed and it looks like it's broken.  Since your seed might have been sourced from angular-seed originally I thought of asking this question.  After firebase and angularfire2 upgrade the seed no more loading the project properly.  

Even a fresh download of angular-seed and adding firebase, angularfire2 don't seem to be working.  May be if you have time you can you can give it a try.

I think your repo is far more coding is already been done, so it would take more time for me to understand a new repo.  Thought of asking you if you could help me to point in right direction.

**Comment by patrickmichalina** [comment]
@ravivit9 do you mean you are using https://github.com/mgechev/angular-seed ?

**Comment by ravivit9** [comment]
yes.

**Comment by patrickmichalina** [comment]
@ravivit9 I have used that seed before, but now I default to this one. There are some MAJOR differences between that one and this one. Namely, Angular-Seed is client only (not server rendered), uses gulp (we use sparky), uses systemJs (we use fuse-box), and other differences.

I have never setup firebase with angular-seed. My assumption would be that your systemjs configuration may not be correct when integrating that library. Alternatively, it could also be the wrong version of firebase. I noticed angular-seed is using Angular v4.4.4.... You may want to reduce the version of firebase you have installed. 

Sorry, don't really think I can support you on this one. You should probably ask this question on the angular-seed repo.

**Comment by ravivit9** [comment]
np, thanks for taking a shot on this.  yes you are right angular-seed itself works fine until I upgrade both firebase and angularfire2.

Will try my best if not I may fall back to my other option.
