### ISSUE TITLE
Can't get App to compile. Keep getting error on firebase auth keys

### ISSUE THREAD

**Issue by nnennajohn** [patrickmichalina/fusebox-angular-universal-starter#250]
Hi. So I get my api keys from Firebase and set it up in the .env file. But it keeps giving me errors that it can't authenticate. I moved things around with no luck. 

I have attack my api keys files and the error. Can you please let me know what I am doing wrong and what exactly is the FB_AUTH_KEY? I tried putting the private key there, but it does not work. Also tried the key ID. Tried generating a new one in Iamadmin, all with no luck. 

I don't want to give up on trying this starter from something that might be an easy fix. 

Thanks. 

![screenshot 2017-10-23 00 36 57](https://user-images.githubusercontent.com/1761197/31877596-ef3def2a-b78b-11e7-9608-980babc1bb54.png)
<img width="872" alt="screenshot 2017-10-23 00 46 26" src="https://user-images.githubusercontent.com/1761197/31877600-f326ed62-b78b-11e7-9548-81423e3d9bde.png">

**Comment by nnennajohn** [comment]
Tried using the client_id from above in the FB_AUTH_KEY and got a different error. 

<img width="988" alt="screenshot 2017-10-23 00 52 16" src="https://user-images.githubusercontent.com/1761197/31877860-e4cad994-b78c-11e7-919e-9aca8ea4c012.png">

**Comment by patrickmichalina** [comment]
@nnennajohn Oh yea sorry about the documentation being lackluster. Probably really confusing!

Anyway, first I would try to use the "Database Secret" as the "FB_AUTH_KEY". You can find this under Project Settings => Service Accounts => Database Secrets

Also, the private key should be of the form "-----BEING PRIVATE KEY--- ", which you had in the first image. This grants your server 100% admin access to your firebase account. If you don't want to grant that level of access, you have to read up on firebase how to reduce this access.

Let me know if you still cannot connect after using the Database Secret as the FB_AUTH_KEY

<img width="1284" alt="screen shot 2017-10-23 at 7 21 11 am" src="https://user-images.githubusercontent.com/6701211/31888771-f19366c4-b7c2-11e7-9560-5fef5a93effd.png">

**Comment by nnennajohn** [comment]
@patrickmichalina , thanks so much for responding. So I went ahead and updated the 

FB_SERVICE_ACCOUNT_PRIVATE_KEY_ID to be "private_key_id"
FB_SERVICE_ACCOUNT_PRIVATE_KEY to be "private_key", I put the whole line this time including begin key

&&

FB_AUTH_KEY to be the database key from the same account in firebase console under service account. 

And unfortunately, I am still getting the same error. tears.....

What to do? Is .env the right file? Is the format right? 

Thanks. 

<img width="1143" alt="screenshot 2017-10-23 10 56 34" src="https://user-images.githubusercontent.com/1761197/31905176-2c4fe070-b7e2-11e7-8034-f0277844c42c.png">

**Comment by nnennajohn** [comment]
Also updated the firebase config in tools/env/base and src/server/data/seed.settings to match your link above. 

And still error. 

Thank you. 

<img width="906" alt="screenshot 2017-10-23 11 13 18" src="https://user-images.githubusercontent.com/1761197/31905687-dd49275a-b7e3-11e7-9412-1990ecd44cb7.png">

**Comment by patrickmichalina** [comment]
I think there may be another step to get service-account credentials to work... Hmmm I did you try the instructions printed in the error about "generating a new set of credentials"?. Maybe the certificate has been revoked?

**Comment by nnennajohn** [comment]
Woo hoo! I finally got this working. I really think this is an awesome project. Considering I spent the whole weekend trying to get my app to work with universal, aot and firebase functions with no luck. Going to try a port of this and fingers crossed, I don't break anything. 

For anyone else that runs into problems. Here's the exact steps you need. 

Update your .env in the root folder with: 

Get from firebase > project settings > service account > Firebase Admin SDK
FB_SERVICE_ACCOUNT_PRIVATE_KEY_ID to be "private_key_id"
FB_SERVICE_ACCOUNT_PRIVATE_KEY to be "private_key"

&&

Get from firebase > project settings > service account > legacy credentials > Database secrets
Note: This says deprecated, so would probably need to update the project at some point.
FB_AUTH_KEY to be the database key from the same account in firebase console

Then update tools/env/base with firebase credentials 
and src/server/data/seed.settings and actually you have to also update other settings files there. So go through all of them and update. 

And viola, you have an amazing seed project up and running. 

Thanks again @patrickmichalina for all you help and for setting this up. I think a lot of people will find it useful.

**Comment by patrickmichalina** [comment]
@nnennajohn awesome! Glad you find it useful. The AngularFire team has just begun working on official support for universal+firebase. Once that is done, I will remove my hacks and integrate the official package. 

Fair warning, you may experience some issues if you use any advanced queries with firebase on the server. I only have [this service](https://github.com/patrickmichalina/fusebox-angular-universal-starter/blob/master/src/server/server.angular-fire.service.ts) in place to render from the server. It mocks a few of the functions that are exposed from firebase. It does not account for all situations. So if you have issues or see obvious mistakes please post them and submit bug fixes :)

I already caught a few more errors and will be fixing them sometimes today

**Comment by nnennajohn** [comment]
@patrickmichalina, You are awesome. Thank you. And yes. Will be glad to submit any bug fixes I find along the way. Thanks again.

**Comment by patrickmichalina** [comment]
@nnennajohn I am working to make adding arbitrary content based pages REALLY easy... Firsts steps are worked out, now I have to do the admin interface and stuff... But I found some issues with the current setup. Every server request is being made by the ADMIN user, but we actually want it made by the UID of the user. I added some basic logic to do this in my PR #258 . You might find it helpful.

**Comment by nnennajohn** [comment]
Thanks so much Patrick. Will def check it out. Please let me know if there is anyway I can helps. Thanks again.

**Comment by patrickmichalina** [comment]
Still a bit of work to be done to squash a view bugs and add more features but you can now create pages with a slug that are content based. Permission are open for the demo, but of course in a real app you'd want to lock those down!

<img width="1233" alt="screen shot 2017-10-28 at 12 12 26 pm" src="https://user-images.githubusercontent.com/6701211/32136791-fbc07702-bbd9-11e7-8609-c6d9d01106ae.png">
<img width="1155" alt="screen shot 2017-10-28 at 12 25 23 pm" src="https://user-images.githubusercontent.com/6701211/32136842-17cb8ee0-bbdb-11e7-9bd0-f6e7ab877252.png">

**Comment by nnennajohn** [comment]
So cool. Thanks for this.
