### ISSUE TITLE
Error: EPERM: operation not permitted, rmdir 

### ISSUE THREAD

**Issue by 108abhishek** [patrickmichalina/fusebox-angular-universal-starter#260]
I tried to run npm start with cmd, power shell in administrator mode and disabled antivirus. I also right clicked the folder and in security tab grant all the permissions.
Still not working.

Node version: 8.4.0
npm version: 5.3.0
windows 8

PS C:\Windows\system32> d:
PS D:\> cd D:\Lara\Projects\AngularProjects\FuseBox\fusebox-angular-universal-starter
PS D:\Lara\Projects\AngularProjects\FuseBox\fusebox-angular-universal-starter> npm start

> fusebox-angular-universal-starter@0.0.0-development start D:\Lara\Projects\AngularProjects\FuseBox\fusebox-angular-uni
versal-starter
> ts-node fuse.ts serve --build-type dev --env-config dev

 Launch "serve"
 Launch "clean"
--- FuseBox 2.3.3 ---
Error: EPERM: operation not permitted, rmdir 'D:\Lara\Projects\AngularProjects\FuseBox\fusebox-angular-universal-starter
\dist\assets\fonts\font-awesome'
PS D:\Lara\Projects\AngularProjects\FuseBox\fusebox-angular-universal-starter>

**Comment by patrickmichalina** [comment]
Can you try installing the project at the root level of your hard disk? I am curious if it is Windows file permissions. Sometimes those can get crazy.

`D:> fusebox-angular-universal-starter`
