### ISSUE TITLE
Serverless (Firebase Functions, AWS Lambda)

### ISSUE THREAD

**Issue by John0x** [patrickmichalina/fusebox-angular-universal-starter#424]
Hello, having a boilerplate with AWS Lambda or another serverless provider support would be awesome :)

I believe angular unviersal would be the perfect fit for a serverless application.

**Comment by patrickmichalina** [comment]
@John0x I think you are correct! My only concern is the latency between requests. I want to experiment with this with Firebase Functions.

**Comment by John0x** [comment]
@patrickmichalina aws lambda/cloud function have a bit of latency, but I don't think that it's too much since the user will typically only request the site once and then the browser takes control.

Would be interesting to see how long one request would take to finish. There are probably some things that should be done differently for cloud functions. For example not using the express server but rendering angular directly.

**Comment by patrickmichalina** [comment]
@John0x I am actively working this, Heroku is great, but since all we truly need is an HTML renderer, Lambda is a better choice. I am reworking this entire starter into one that is NOT opinionated. I will post the new repo once I have the first pass complete!

**Comment by patrickmichalina** [comment]
@John0x luckily there is an express lambda wrapper, which can be a good start, even though it would be ideal to render without express.

**Comment by patrickmichalina** [comment]
I got a lot of this solved, but the issue is all these providers are stuck on Node 6. Until we get to at least Node 8, It is too difficult to get his working with a clean folder structure

**Comment by patrickmichalina** [comment]
Finally!

https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/

**Comment by dalu** [comment]
how would I get rid of firebase here?
is it sufficient to just `yarn remove firebase firebase-admin`? Or is firebase integrated deeper in this?
I have written a generator for Go endpoints and angular services so firebase isn't needed.

**Comment by patrickmichalina** [comment]
@dalu I'd checkout this repo https://github.com/patrickmichalina/fusing-angular

Its mostly the same build tooling, but without firebase!

**Comment by dalu** [comment]
thanks, now I just need to get rid of Heroku :D haha (because I use my own infra)
sorry, I'm derailing the original issue here. I'll probably have to create an issue on that repo, if I run into any problems.
