### ISSUE TITLE
Firebase issue

### ISSUE THREAD

**Issue by billbarni** [patrickmichalina/fusebox-angular-universal-starter#479]
I get this error when starting the app. Im using the credencials from the default Firebase Service Account created with the app. ` App Engine default service account `.

Is there any additional permission I must set to the account? Must I create a new one with differente permissions?

`FIREBASE WARNING: Provided authentication credentials for the app named "admin" are invalid. This usually indicates your app was not initialized correctly. Make sure the "credential" property provided to initializeApp() is authorized to access the specified "databaseURL" and is from the correct project.`

**Comment by billbarni** [comment]
Sorry, I missed some other configuration that was unlisted in the readme file.

**Comment by patrickmichalina** [comment]
Yeah, sorry my docs aren't very clear about this. In firebase console go to this area and download the JSON auth file.

<img width="1316" alt="screen shot 2018-02-10 at 10 16 00 am" src="https://user-images.githubusercontent.com/6701211/36064097-853c9ba0-0e4b-11e8-9e9a-c79e62dbb968.png">

Take that JSON and place the values into the `src/server/service-account.json`(you can see the one used in the demo app here https://github.com/patrickmichalina/fusebox-angular-universal-starter/blob/master/src/server/service-account.json)

Take those two secret values, and place them in the `.env`. This is a security thing so you aren't storing in source control. If you want to store in source, thats up to you.

Hope that helps!
