### ISSUE TITLE
How to get a clean code without firebase?

### ISSUE THREAD

**Issue by dewei-xiang** [patrickmichalina/fusebox-angular-universal-starter#519]
Hi,

I want a bisic code without firebase, how to remove all of them, is there a branch without firebase?

**Comment by patrickmichalina** [comment]
Good idea. I should make a non-firebase branch :)

**Comment by dewei-xiang** [comment]
thank you. I feel firebase is deeply integrated with the current code and it's hard to remove it from the project. it's very nice to have a non-firebase version.

**Comment by patrickmichalina** [comment]
@xiangdewei you are right! It is far too integrated.

My original goal of this repo was for getting Fusebox and Jest and universal into a nice little package for fast development (not slow webpack/karma)... But it grew into something else. I would like to trim it back into JUST the minimal starter. Hopefully in the next couple weeks.

Thanks

**Comment by patrickmichalina** [comment]
@xiangdewei I have started a clean repo with updated tools and AOT support (production bundle down to 175kb!). Please go here for the empty repo https://github.com/patrickmichalina/fusing-angular
