### ISSUE TITLE
Debug Jest tests either in Browser or with VSCode?

### ISSUE THREAD

**Issue by asadsahi** [patrickmichalina/fusebox-angular-universal-starter#531]
Is there any way to debug jest tests. I have found some resources online which have some vscode launch config to debug javascript based jest tests. But It would be really nice if we could debug angular+typescript tests wither in browser or vscode?

**Comment by patrickmichalina** [comment]
That would be really cool! I think there is a Chrome plugin that helps to achieve this? I haven't looked into this before, but may give it a shot sometime. Let us know if you figure it out.

**Comment by asadsahi** [comment]
@patrickmichalina been struggling since yesterday, but not getting anywhere. :)

Just an idea but I was thinking if there is an executable like ts-node which runs typescript jest tests, then we can try setting that as program in launch.json of vscode. Don't want to compile all the typescript jest tests and debug through sourcemaps since that will be very slow every time we make a change. Having said that haven't got anything working yet. :(

**Comment by patrickmichalina** [comment]
@asadsahi I got this working in another repo

https://github.com/patrickmichalina/fusing-angular/commit/e7d5f671e761b2c17c9f73570330baffed24d018

**Comment by asadsahi** [comment]
@patrickmichalina I had similar config trying to somehow get breakpoint hit in VS code but still no luck. I tried following your config. Here is what my config and result looks like:

![image](https://user-images.githubusercontent.com/3470892/37878840-d34b49b2-3066-11e8-9693-d15ff93b2d2d.png)

Have you managed to hit breakpoints in typescript files from VS code? Is there anything else I am missing.

Note: The only difference I have is the jest configuration in your case in a json file (which I am ommiting), but in my case it is in package.json.

**Comment by patrickmichalina** [comment]
@asadsahi I was able to hit breakpoints in vscode (and inspect variable, etc). Worked great. Not sure why its not working on your end :(

**Comment by patrickmichalina** [comment]
<img width="1660" alt="screen shot 2018-03-26 at 9 41 22 pm" src="https://user-images.githubusercontent.com/6701211/37943754-7bf599aa-313e-11e8-81dd-2aca2d237527.png">

**Comment by asadsahi** [comment]
@patrickmichalina really wanted to see this in action in your repo, but getting this error while trying to npm install:

![image](https://user-images.githubusercontent.com/3470892/38026930-e6897406-3285-11e8-87a6-b454ebbd469b.png)

**Comment by patrickmichalina** [comment]
The GYP errors typically occur in windows environments when compiling binaries. I’d recommend you get this fixed since other packages may cause this issue for you as well.

There is a guide online on how to fix this.

**Comment by billbarni** [comment]
@asadsahi to get through this GYP errors you need to install windows build tools:

`npm install --global --production windows-build-tools`

**it will take a long time**, after that reboot the computer
